DROP TABLE CUSTOMER IF EXISTS;
DROP TABLE DISTRICT IF EXISTS;
DROP TABLE HISTORY IF EXISTS;
DROP TABLE ITEM IF EXISTS;
DROP TABLE NEW_ORDER IF EXISTS;
DROP TABLE OORDER IF EXISTS;
DROP TABLE ORDER_LINE IF EXISTS;
DROP TABLE STOCK IF EXISTS;
DROP TABLE WAREHOUSE IF EXISTS;
DROP TABLE region IF EXISTS;
DROP TABLE nation IF EXISTS;
DROP TABLE supplier IF EXISTS;

CREATE TABLE CUSTOMER (
  C_W_ID INT NOT NULL,
  C_D_ID INT NOT NULL,
  C_ID INT NOT NULL,
  C_DISCOUNT DECIMAL(4,4) NOT NULL,
  C_CREDIT VARCHAR(2) NOT NULL,
  C_LAST VARCHAR(16) NOT NULL,
  C_FIRST VARCHAR(16) NOT NULL,
  C_CREDIT_LIM DECIMAL(12,2) NOT NULL,
  C_BALANCE DECIMAL(12,2) NOT NULL,
  C_YTD_PAYMENT DECIMAL(12,2) NOT NULL,
  C_PAYMENT_CNT INT NOT NULL,
  C_DELIVERY_CNT INT NOT NULL,
  C_STREET_1 VARCHAR(20) NOT NULL,
  C_STREET_2 VARCHAR(20) NOT NULL,
  C_CITY VARCHAR(20) NOT NULL,
  C_STATE VARCHAR(2) NOT NULL,
  C_ZIP VARCHAR(9) NOT NULL,
  C_PHONE VARCHAR(16) NOT NULL,
  C_SINCE TIMESTAMP(3) NOT NULL,
  C_MIDDLE VARCHAR(2) NOT NULL,
  C_DATA VARCHAR(500) NOT NULL,
  PRIMARY KEY (C_W_ID,C_D_ID,C_ID)
);

CREATE INDEX IDX_CUSTOMER_NAME ON CUSTOMER (C_W_ID,C_D_ID,C_LAST,C_FIRST);
PARTITION TABLE CUSTOMER ON COLUMN C_W_ID;

CREATE TABLE DISTRICT (
  D_W_ID INT NOT NULL,
  D_ID INT NOT NULL,
  D_YTD DECIMAL(12,2) NOT NULL,
  D_TAX DECIMAL(4,4) NOT NULL,
  D_NEXT_O_ID INT NOT NULL,
  D_NAME VARCHAR(10) NOT NULL,
  D_STREET_1 VARCHAR(20) NOT NULL,
  D_STREET_2 VARCHAR(20) NOT NULL,
  D_CITY VARCHAR(20) NOT NULL,
  D_STATE VARCHAR(2) NOT NULL,
  D_ZIP VARCHAR(9) NOT NULL,
  PRIMARY KEY (D_W_ID,D_ID)
);

PARTITION TABLE DISTRICT ON COLUMN D_W_ID;

CREATE TABLE HISTORY (
  H_C_ID INT NOT NULL,
  H_C_D_ID INT NOT NULL,
  H_C_W_ID INT NOT NULL,
  H_D_ID INT NOT NULL,
  H_W_ID INT NOT NULL,
  H_DATE TIMESTAMP(3) NOT NULL ,
  H_AMOUNT DECIMAL(6,2) NOT NULL,
  H_DATA VARCHAR(24) NOT NULL
);

PARTITION TABLE HISTORY ON COLUMN H_W_ID;

CREATE TABLE ITEM (
  I_ID INT NOT NULL,
  I_NAME VARCHAR(24) NOT NULL,
  I_PRICE DECIMAL(5,2) NOT NULL,
  I_DATA VARCHAR(50) NOT NULL,
  I_IM_ID INT NOT NULL,
  PRIMARY KEY (I_ID)
);


CREATE TABLE NEW_ORDER (
  NO_W_ID INT NOT NULL,
  NO_D_ID INT NOT NULL,
  NO_O_ID INT NOT NULL,
  PRIMARY KEY (NO_W_ID,NO_D_ID,NO_O_ID)
);

PARTITION TABLE NEW_ORDER ON COLUMN NO_W_ID;

CREATE TABLE OORDER (
  O_W_ID INT NOT NULL,
  O_D_ID INT NOT NULL,
  O_ID INT NOT NULL,
  O_C_ID INT NOT NULL,
  O_CARRIER_ID INT DEFAULT NULL,
  O_OL_CNT DECIMAL(2,0) NOT NULL,
  O_ALL_LOCAL DECIMAL(1,0) NOT NULL,
  O_ENTRY_D TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (O_W_ID,O_D_ID,O_ID),
  UNIQUE (O_W_ID,O_D_ID,O_C_ID,O_ID)
);

CREATE INDEX IDX_ORDER ON OORDER (O_W_ID,O_D_ID,O_C_ID,O_ID);
PARTITION TABLE OORDER ON COLUMN O_W_ID;

CREATE TABLE ORDER_LINE (
  OL_W_ID INT NOT NULL,
  OL_D_ID INT NOT NULL,
  OL_O_ID INT NOT NULL,
  OL_NUMBER INT NOT NULL,
  OL_I_ID INT NOT NULL,
  OL_DELIVERY_D TIMESTAMP(3),
  OL_AMOUNT DECIMAL(12,2) NOT NULL,
  OL_SUPPLY_W_ID INT NOT NULL,
  OL_QUANTITY DECIMAL(2,0) NOT NULL,
  OL_DIST_INFO VARCHAR(24) NOT NULL,
  PRIMARY KEY (OL_W_ID,OL_D_ID,OL_O_ID,OL_NUMBER)
);

PARTITION TABLE ORDER_LINE ON COLUMN OL_W_ID;

CREATE TABLE STOCK (
  S_W_ID INT NOT NULL,
  S_I_ID INT NOT NULL,
  S_QUANTITY DECIMAL(4,0) NOT NULL,
  S_YTD INT NOT NULL,
  S_ORDER_CNT INT NOT NULL,
  S_REMOTE_CNT INT NOT NULL,
  S_DATA VARCHAR(50) NOT NULL,
  S_DIST_01 VARCHAR(24) NOT NULL,
  S_DIST_02 VARCHAR(24) NOT NULL,
  S_DIST_03 VARCHAR(24) NOT NULL,
  S_DIST_04 VARCHAR(24) NOT NULL,
  S_DIST_05 VARCHAR(24) NOT NULL,
  S_DIST_06 VARCHAR(24) NOT NULL,
  S_DIST_07 VARCHAR(24) NOT NULL,
  S_DIST_08 VARCHAR(24) NOT NULL,
  S_DIST_09 VARCHAR(24) NOT NULL,
  S_DIST_10 VARCHAR(24) NOT NULL,
  PRIMARY KEY (S_W_ID,S_I_ID)
);

PARTITION TABLE STOCK ON COLUMN S_W_ID;

CREATE TABLE WAREHOUSE (
  W_ID INT NOT NULL,
  W_YTD DECIMAL(12,2) NOT NULL,
  W_TAX DECIMAL(4,4) NOT NULL,
  W_NAME VARCHAR(10) NOT NULL,
  W_STREET_1 VARCHAR(20) NOT NULL,
  W_STREET_2 VARCHAR(20) NOT NULL,
  W_CITY VARCHAR(20) NOT NULL,
  W_STATE VARCHAR(2) NOT NULL,
  W_ZIP VARCHAR(9) NOT NULL,
  PRIMARY KEY (W_ID)
);

PARTITION TABLE WAREHOUSE ON COLUMN W_ID;

create table REGION (
   r_regionkey int not null,
   r_name VARCHAR(55) not null,
   r_comment VARCHAR(152) not null,
   PRIMARY KEY ( r_regionkey )
);

create table NATION (
   n_nationkey int not null,
   n_name VARCHAR(25) not null,
   n_regionkey int not null,
   n_comment VARCHAR(152) not null,
   PRIMARY KEY ( n_nationkey )
);

create table SUPPLIER (
   su_suppkey int not null,
   su_name VARCHAR(25) not null,
   su_address varchar(40) not null,
   su_nationkey int not null,
   su_phone VARCHAR(15) not null,
   su_acctbal DECIMAL(12,2) not null,
   su_comment VARCHAR(101) not null,
   PRIMARY KEY ( su_suppkey )
);

